from abc import ABC, abstractmethod
class Connection(ABC):
    @abstractmethod
    async def connect(self): ...
    @abstractmethod
    async def run(self, command: str) -> str: ...
    @abstractmethod
    async def close(self): ...
