from alembic import op
import sqlalchemy as sa

revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    op.create_table("credentials", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("name", sa.String(255), nullable=False, unique=True), sa.Column("type", sa.String(32), nullable=False), sa.Column("username", sa.String(255), nullable=False), sa.Column("domain", sa.String(255)), sa.Column("encrypted_secret", sa.Text(), nullable=False), sa.Column("port", sa.Integer()), sa.Column("verify_tls", sa.Boolean(), nullable=False, server_default=sa.true()), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False))
    op.create_table("assets", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("hostname", sa.String(255), nullable=False), sa.Column("fqdn", sa.String(255)), sa.Column("ip_address", sa.String(64), nullable=False), sa.Column("platform", sa.String(32), nullable=False), sa.Column("credential_id", sa.Integer(), sa.ForeignKey("credentials.id", ondelete="SET NULL")), sa.Column("enabled", sa.Boolean(), nullable=False, server_default=sa.true()), sa.Column("scan_interval", sa.Integer(), nullable=False, server_default="86400"), sa.Column("description", sa.Text()), sa.Column("last_scan_at", sa.DateTime(timezone=True)), sa.Column("last_scan_attempt_at", sa.DateTime(timezone=True)))
    op.create_index("ix_assets_hostname", "assets", ["hostname"]); op.create_index("ix_assets_ip_address", "assets", ["ip_address"]); op.create_index("ix_assets_platform", "assets", ["platform"]); op.create_index("ix_assets_enabled", "assets", ["enabled"])
    op.create_table("scans", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("asset_id", sa.Integer(), sa.ForeignKey("assets.id", ondelete="CASCADE"), nullable=False), sa.Column("started_at", sa.DateTime(timezone=True)), sa.Column("finished_at", sa.DateTime(timezone=True)), sa.Column("status", sa.String(32), nullable=False, server_default="QUEUED"), sa.Column("error", sa.Text()), sa.Column("software_count", sa.Integer(), nullable=False, server_default="0"))
    op.create_index("ix_scans_asset_id", "scans", ["asset_id"]); op.create_index("ix_scans_status", "scans", ["status"]); op.create_index("ix_scans_asset_started", "scans", ["asset_id", "started_at"])
    op.create_table("software", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("asset_id", sa.Integer(), sa.ForeignKey("assets.id", ondelete="CASCADE"), nullable=False), sa.Column("name", sa.String(512), nullable=False), sa.Column("version", sa.String(512), nullable=False), sa.Column("vendor", sa.String(512)), sa.Column("source", sa.String(128)), sa.Column("ecosystem", sa.String(128)), sa.Column("architecture", sa.String(64)), sa.Column("evidence", sa.JSON()), sa.Column("first_seen", sa.DateTime(timezone=True), nullable=False), sa.Column("last_seen", sa.DateTime(timezone=True), nullable=False), sa.Column("active", sa.Boolean(), nullable=False, server_default=sa.true()), sa.UniqueConstraint("asset_id", "name", "source", name="uq_asset_software_identity"))
    op.create_index("ix_software_asset_id", "software", ["asset_id"]); op.create_index("ix_software_active", "software", ["active"]); op.create_index("ix_software_asset_name", "software", ["asset_id", "name"])
    op.create_table("inventory_snapshots", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("asset_id", sa.Integer(), sa.ForeignKey("assets.id", ondelete="CASCADE"), nullable=False), sa.Column("scan_id", sa.Integer(), sa.ForeignKey("scans.id", ondelete="CASCADE"), nullable=False), sa.Column("collected_at", sa.DateTime(timezone=True), nullable=False), sa.Column("payload", sa.JSON(), nullable=False))
    op.create_index("ix_inventory_snapshots_asset_id", "inventory_snapshots", ["asset_id"]); op.create_index("ix_inventory_snapshots_scan_id", "inventory_snapshots", ["scan_id"])
    op.create_table("inventory_events", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("asset_id", sa.Integer(), sa.ForeignKey("assets.id", ondelete="CASCADE"), nullable=False), sa.Column("scan_id", sa.Integer(), sa.ForeignKey("scans.id", ondelete="CASCADE"), nullable=False), sa.Column("event_type", sa.String(32), nullable=False), sa.Column("name", sa.String(512), nullable=False), sa.Column("old_version", sa.String(512)), sa.Column("new_version", sa.String(512)), sa.Column("source", sa.String(128)), sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False))
    op.create_index("ix_inventory_events_asset_id", "inventory_events", ["asset_id"]); op.create_index("ix_inventory_events_scan_id", "inventory_events", ["scan_id"]); op.create_index("ix_inventory_events_event_type", "inventory_events", ["event_type"])

def downgrade():
    op.drop_table("inventory_events"); op.drop_table("inventory_snapshots"); op.drop_table("software"); op.drop_table("scans"); op.drop_table("assets"); op.drop_table("credentials")
